version: "3.8"

services:
    backend:
        image: dev-academy2023-backend
        ports:
            - 3100:3100
        environment:
            - PORT=3100
            - MONGO_URI=mongodb://user1:Passw0rd@mongo:27017/
            - FILE_PATH="../files/"
        volumes:
            - files:/home/node/app

    mongo:
        image: mongo
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME: user1
            - MONGO_INITDB_ROOT_PASSWORD: Passw0rd
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME: user1
            - ME_CONFIG_MONGODB_ADMINPASSWORD: Passw0rd
            - ME_CONFIG_MONGODB_URL: mongodb://user1:Passw0rd@mongo:27017/

volumes:
    files:
